# Site settings
title: Library
description: >
  Library Image Archive
baseurl: ""
url: "https://i.lucadicarlo.com"
enforce_ssl: i.lucadicarlo.com
production_url: "https://i.lucadicarlo.com"
# Collections
#collections:
#  books:
#    output: false

sass:
  style: compressed
