# Site settings
title: Library
description: >
  Library Image Archive
baseurl: ""
url: "http://i.lucadicarlo.com"
enforce_ssl: i.lucadicarlo.com

# Collections
#collections:
#  books:
#    output: false

sass:
  style: compressed
